# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\active.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(758, 524)
        self.active_grid = QtWidgets.QGridLayout(Form)
        self.active_grid.setContentsMargins(0, 0, 0, 0)
        self.active_grid.setObjectName("active_grid")
        self.nav_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_frame.sizePolicy().hasHeightForWidth())
        self.nav_frame.setSizePolicy(sizePolicy)
        self.nav_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nav_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nav_frame.setObjectName("nav_frame")
        self.nav_frame_layout = QtWidgets.QGridLayout(self.nav_frame)
        self.nav_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.nav_frame_layout.setSpacing(0)
        self.nav_frame_layout.setObjectName("nav_frame_layout")
        self.active_grid.addWidget(self.nav_frame, 0, 0, 1, 1)
        self.stack = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack.sizePolicy().hasHeightForWidth())
        self.stack.setSizePolicy(sizePolicy)
        self.stack.setObjectName("stack")
        self.active_grid.addWidget(self.stack, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
