# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\confirm_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_confirmation(object):
    def setupUi(self, delete_confirmation):
        delete_confirmation.setObjectName("delete_confirmation")
        delete_confirmation.resize(600, 200)
        delete_confirmation.setMinimumSize(QtCore.QSize(600, 200))
        delete_confirmation.setMaximumSize(QtCore.QSize(600, 200))
        self.layout = QtWidgets.QGridLayout(delete_confirmation)
        self.layout.setObjectName("layout")
        self.text_label = QtWidgets.QLabel(delete_confirmation)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.text_label.setFont(font)
        self.text_label.setText("")
        self.text_label.setWordWrap(True)
        self.text_label.setObjectName("text_label")
        self.layout.addWidget(self.text_label, 0, 1, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(delete_confirmation)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.button_box.setObjectName("button_box")
        self.layout.addWidget(self.button_box, 1, 1, 1, 1)
        self.icon_label = QtWidgets.QLabel(delete_confirmation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_label.sizePolicy().hasHeightForWidth())
        self.icon_label.setSizePolicy(sizePolicy)
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.layout.addWidget(self.icon_label, 0, 0, 1, 1)

        self.retranslateUi(delete_confirmation)
        self.button_box.accepted.connect(delete_confirmation.accept)
        self.button_box.rejected.connect(delete_confirmation.reject)
        QtCore.QMetaObject.connectSlotsByName(delete_confirmation)

    def retranslateUi(self, delete_confirmation):
        _translate = QtCore.QCoreApplication.translate
        delete_confirmation.setWindowTitle(_translate("delete_confirmation", "Confirm deletion"))
