# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\drag_drop.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 403)
        self.drag_drop_layout = QtWidgets.QGridLayout(Form)
        self.drag_drop_layout.setVerticalSpacing(10)
        self.drag_drop_layout.setObjectName("drag_drop_layout")
        self.info_text_2 = QtWidgets.QLabel(Form)
        self.info_text_2.setMinimumSize(QtCore.QSize(200, 0))
        self.info_text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.info_text_2.setObjectName("info_text_2")
        self.drag_drop_layout.addWidget(self.info_text_2, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.drag_drop_layout.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.drag_drop_layout.addItem(spacerItem1, 0, 1, 1, 1)
        self.browse = QtWidgets.QPushButton(Form)
        self.browse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.browse.setObjectName("browse")
        self.drag_drop_layout.addWidget(self.browse, 3, 1, 1, 1)
        self.info_text = QtWidgets.QLabel(Form)
        self.info_text.setMinimumSize(QtCore.QSize(200, 0))
        self.info_text.setAlignment(QtCore.Qt.AlignCenter)
        self.info_text.setObjectName("info_text")
        self.drag_drop_layout.addWidget(self.info_text, 1, 1, 1, 1)
        self.spacer_frame_right = QtWidgets.QFrame(Form)
        self.spacer_frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spacer_frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spacer_frame_right.setObjectName("spacer_frame_right")
        self.drag_drop_layout.addWidget(self.spacer_frame_right, 1, 2, 3, 1)
        self.spacer_frame_left = QtWidgets.QFrame(Form)
        self.spacer_frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spacer_frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spacer_frame_left.setObjectName("spacer_frame_left")
        self.drag_drop_layout.addWidget(self.spacer_frame_left, 1, 0, 3, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.info_text_2.setText(_translate("Form", "or"))
        self.browse.setText(_translate("Form", "Browse..."))
        self.info_text.setText(_translate("Form", "Drag & Drop visualisations here"))
