# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\export.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_export_name(object):
    def setupUi(self, export_name):
        export_name.setObjectName("export_name")
        export_name.resize(434, 122)
        self.gridLayout = QtWidgets.QGridLayout(export_name)
        self.gridLayout.setObjectName("gridLayout")
        self.name_edit = QtWidgets.QLineEdit(export_name)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(export_name)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.warning = QtWidgets.QLabel(export_name)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.warning.setFont(font)
        self.warning.setTextFormat(QtCore.Qt.RichText)
        self.warning.setWordWrap(True)
        self.warning.setObjectName("warning")
        self.gridLayout.addWidget(self.warning, 1, 0, 1, 2)

        self.retranslateUi(export_name)
        self.buttonBox.accepted.connect(export_name.accept)
        self.buttonBox.rejected.connect(export_name.reject)
        QtCore.QMetaObject.connectSlotsByName(export_name)

    def retranslateUi(self, export_name):
        _translate = QtCore.QCoreApplication.translate
        export_name.setWindowTitle(_translate("export_name", "Enter export folder name"))
        self.warning.setText(_translate("export_name", "<html><head/><body><p><span style=\" color:#ff0000;\">A folder with this name already exists. Please choose another name or move the existing folder.</span></p></body></html>"))
