# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\import_existing.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportForm(object):
    def setupUi(self, ImportForm):
        ImportForm.setObjectName("ImportForm")
        ImportForm.resize(400, 440)
        self.import_list_layout = QtWidgets.QGridLayout(ImportForm)
        self.import_list_layout.setContentsMargins(10, 10, 10, 10)
        self.import_list_layout.setSpacing(5)
        self.import_list_layout.setObjectName("import_list_layout")
        self.import_button = QtWidgets.QPushButton(ImportForm)
        self.import_button.setEnabled(False)
        self.import_button.setObjectName("import_button")
        self.import_list_layout.addWidget(self.import_button, 2, 0, 1, 1)
        self.list = QtWidgets.QListWidget(ImportForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.list.sizePolicy().hasHeightForWidth())
        self.list.setSizePolicy(sizePolicy)
        self.list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list.setProperty("showDropIndicator", False)
        self.list.setObjectName("list")
        self.import_list_layout.addWidget(self.list, 0, 0, 1, 1)
        self.desc = QtWidgets.QTextEdit(ImportForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.desc.sizePolicy().hasHeightForWidth())
        self.desc.setSizePolicy(sizePolicy)
        self.desc.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.desc.setObjectName("desc")
        self.import_list_layout.addWidget(self.desc, 1, 0, 1, 1)

        self.retranslateUi(ImportForm)
        QtCore.QMetaObject.connectSlotsByName(ImportForm)

    def retranslateUi(self, ImportForm):
        _translate = QtCore.QCoreApplication.translate
        ImportForm.setWindowTitle(_translate("ImportForm", "Select position to import"))
        self.import_button.setText(_translate("ImportForm", "Import"))
        self.desc.setPlaceholderText(_translate("ImportForm", "Waiting for position to be selected..."))
