# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\load.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_load_form(object):
    def setupUi(self, load_form):
        load_form.setObjectName("load_form")
        load_form.resize(537, 553)
        self.load_layout = QtWidgets.QGridLayout(load_form)
        self.load_layout.setContentsMargins(10, 10, 10, 10)
        self.load_layout.setSpacing(10)
        self.load_layout.setObjectName("load_layout")
        self.import_position = QtWidgets.QPushButton(load_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.import_position.sizePolicy().hasHeightForWidth())
        self.import_position.setSizePolicy(sizePolicy)
        self.import_position.setObjectName("import_position")
        self.load_layout.addWidget(self.import_position, 1, 4, 1, 1)
        self.new_position = QtWidgets.QPushButton(load_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.new_position.sizePolicy().hasHeightForWidth())
        self.new_position.setSizePolicy(sizePolicy)
        self.new_position.setObjectName("new_position")
        self.load_layout.addWidget(self.new_position, 1, 3, 1, 1)
        self.position_dropdown = QtWidgets.QComboBox(load_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.position_dropdown.sizePolicy().hasHeightForWidth())
        self.position_dropdown.setSizePolicy(sizePolicy)
        self.position_dropdown.setFocusPolicy(QtCore.Qt.NoFocus)
        self.position_dropdown.setObjectName("position_dropdown")
        self.load_layout.addWidget(self.position_dropdown, 1, 1, 1, 1)
        self.load_tabs = QtWidgets.QTabWidget(load_form)
        self.load_tabs.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.load_tabs.sizePolicy().hasHeightForWidth())
        self.load_tabs.setSizePolicy(sizePolicy)
        self.load_tabs.setAcceptDrops(True)
        self.load_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.load_tabs.setTabBarAutoHide(True)
        self.load_tabs.setObjectName("load_tabs")
        self.load_layout.addWidget(self.load_tabs, 3, 1, 1, 4)
        self.selection_info = QtWidgets.QTextEdit(load_form)
        self.selection_info.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.selection_info.sizePolicy().hasHeightForWidth())
        self.selection_info.setSizePolicy(sizePolicy)
        self.selection_info.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selection_info.setReadOnly(True)
        self.selection_info.setObjectName("selection_info")
        self.load_layout.addWidget(self.selection_info, 2, 1, 1, 4)
        self.edit_position = QtWidgets.QPushButton(load_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.edit_position.sizePolicy().hasHeightForWidth())
        self.edit_position.setSizePolicy(sizePolicy)
        self.edit_position.setObjectName("edit_position")
        self.load_layout.addWidget(self.edit_position, 1, 2, 1, 1)

        self.retranslateUi(load_form)
        self.load_tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(load_form)

    def retranslateUi(self, load_form):
        _translate = QtCore.QCoreApplication.translate
        load_form.setWindowTitle(_translate("load_form", "Form"))
        self.import_position.setText(_translate("load_form", "Import Position"))
        self.new_position.setText(_translate("load_form", "Create New Position"))
        self.selection_info.setPlaceholderText(_translate("load_form", "Waiting for position to be selected..."))
        self.edit_position.setText(_translate("load_form", "Edit Position"))
