# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\navbutton.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(160, 60)
        self.layout = QtWidgets.QHBoxLayout(Form)
        self.layout.setObjectName("layout")
        self.nav_subframe = QtWidgets.QFrame(Form)
        self.nav_subframe.setMinimumSize(QtCore.QSize(0, 32))
        self.nav_subframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nav_subframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nav_subframe.setObjectName("nav_subframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.nav_subframe)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nav_icon = QtWidgets.QLabel(self.nav_subframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_icon.sizePolicy().hasHeightForWidth())
        self.nav_icon.setSizePolicy(sizePolicy)
        self.nav_icon.setText("")
        self.nav_icon.setObjectName("nav_icon")
        self.horizontalLayout.addWidget(self.nav_icon)
        self.nav_text = QtWidgets.QLabel(self.nav_subframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_text.sizePolicy().hasHeightForWidth())
        self.nav_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.nav_text.setFont(font)
        self.nav_text.setText("")
        self.nav_text.setObjectName("nav_text")
        self.horizontalLayout.addWidget(self.nav_text)
        self.layout.addWidget(self.nav_subframe, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass
