# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\recovery.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecoverDialog(object):
    def setupUi(self, RecoverDialog):
        RecoverDialog.setObjectName("RecoverDialog")
        RecoverDialog.resize(400, 199)
        self.gridLayout = QtWidgets.QGridLayout(RecoverDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(RecoverDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.icon_label = QtWidgets.QLabel(RecoverDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_label.sizePolicy().hasHeightForWidth())
        self.icon_label.setSizePolicy(sizePolicy)
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.gridLayout.addWidget(self.icon_label, 0, 0, 2, 1)
        self.text_label = QtWidgets.QLabel(RecoverDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_label.sizePolicy().hasHeightForWidth())
        self.text_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.text_label.setFont(font)
        self.text_label.setWordWrap(True)
        self.text_label.setObjectName("text_label")
        self.gridLayout.addWidget(self.text_label, 0, 1, 1, 1)
        self.details_text = QtWidgets.QLabel(RecoverDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.details_text.setFont(font)
        self.details_text.setText("")
        self.details_text.setObjectName("details_text")
        self.gridLayout.addWidget(self.details_text, 1, 1, 1, 1)

        self.retranslateUi(RecoverDialog)
        self.buttonBox.accepted.connect(RecoverDialog.accept)
        self.buttonBox.rejected.connect(RecoverDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RecoverDialog)

    def retranslateUi(self, RecoverDialog):
        _translate = QtCore.QCoreApplication.translate
        RecoverDialog.setWindowTitle(_translate("RecoverDialog", "File Recovery"))
        self.text_label.setText(_translate("RecoverDialog", "An unexpected shutdown has been detected since the last time you used OptiCORD. Would you like to attempt recovery of the last file you were working on?"))
