# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GIT\OptiCORD v2 (Development)\ui\unsaved_changes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unsaved_changes(object):
    def setupUi(self, unsaved_changes):
        unsaved_changes.setObjectName("unsaved_changes")
        unsaved_changes.resize(600, 200)
        unsaved_changes.setMinimumSize(QtCore.QSize(600, 200))
        unsaved_changes.setMaximumSize(QtCore.QSize(600, 200))
        self.layout = QtWidgets.QGridLayout(unsaved_changes)
        self.layout.setObjectName("layout")
        self.text_label = QtWidgets.QLabel(unsaved_changes)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.text_label.setFont(font)
        self.text_label.setWordWrap(True)
        self.text_label.setObjectName("text_label")
        self.layout.addWidget(self.text_label, 0, 1, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(unsaved_changes)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.button_box.setObjectName("button_box")
        self.layout.addWidget(self.button_box, 1, 1, 1, 1)
        self.icon_label = QtWidgets.QLabel(unsaved_changes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_label.sizePolicy().hasHeightForWidth())
        self.icon_label.setSizePolicy(sizePolicy)
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.layout.addWidget(self.icon_label, 0, 0, 1, 1)

        self.retranslateUi(unsaved_changes)
        QtCore.QMetaObject.connectSlotsByName(unsaved_changes)

    def retranslateUi(self, unsaved_changes):
        _translate = QtCore.QCoreApplication.translate
        unsaved_changes.setWindowTitle(_translate("unsaved_changes", "Unsaved Changes Found"))
        self.text_label.setText(_translate("unsaved_changes", "Warning! The file you are working on has unsaved changes! Choose to save the changes, discard them, or cancel and return to editing."))
